name: 'Deploy'

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Deploy
        env:
          PRODUCTION_SERVER: ${{ secrets.PRODUCTION_SERVER }}
          PRODUCTION_USERNAME: ${{ secrets.PRODUCTION_USERNAME }}
          PRODUCTION_PASSWORD: ${{ secrets.PRODUCTION_PASSWORD }}
          STAGING_SERVER: ${{ secrets.STAGING_SERVER }}
          STAGING_API_KEY: ${{ secrets.STAGING_API_KEY }}
        run: python3 sync.py
