name: 'Deploy'

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Setup credentials
        run: |
          touch .env
          echo "PRODUCTION_SERVER=${{ secrets.PRODUCTION_SERVER }}" >> .env
          echo "PRODUCTION_USERNAME=${{ secrets.PRODUCTION_USERNAME }}" >> .env
          echo "PRODUCTION_PASSWORD=${{ secrets.PRODUCTION_PASSWORD }}" >> .env
          echo "STAGING_SERVER=${{ secrets.STAGING_SERVER }}" >> .env
          echo "STAGING_API_KEY=${{ secrets.STAGING_API_KEY }}" >> .env
      - name: Deploy
        run: python3 sync.py
